### ISSUE TITLE
[Support]: record_linkage error - internal service error

### ISSUE THREAD

**Issue by yechana** [CDCgov/phdi-azure#131]
### Problem

Error at `record_linkage` stage, of type "User configuration issue", error code 2108.

Full error message: `Internal Server Error`

Affected run IDs:

1. 11dc29ee-f105-11ed-a37e-00155df253a8
2. 15fa5622-f105-11ed-9d05-00155df253a8
3. 1659dd18-f105-11ed-b68a-00155df253a8
4. 189da730-f105-11ed-bee5-00155df253a8
5. 18a955d0-f105-11ed-bb45-00155df253a8
6. 19cb9cb6-f105-11ed-bb45-00155df253a8
7. 19d4fc34-f105-11ed-9d05-00155df253a8
8. 1a63e228-f105-11ed-bee5-00155df253a8
9. 1a932c22-f105-11ed-9d05-00155df253a8
10. 1d8d03bc-f105-11ed-b68a-00155df253a8
11. 22ca3386-f105-11ed-b4f7-00155daa18ba

### Impact

The runs were not successful

### Steps to Reproduce

1. Rerun the listed run IDs

### Intended outcome

The runs should not fail

### Desktop

OS: Windows 10
Browser: Chrome
Version 113.0.5672.64

### Review ticket for PHI

- [X] I have reviewed the information in this ticket and can confirm that no PHI has been included.

**Comment by achang-lac** [comment]
Adding that 7 out of my 20 messages failed due to the the same reason mentioned in this ticket, "record_linkage failed: Internal Server Error" (Error Code 2108)

Affected Run IDs:
1. 12a7037c-f11d-11ed-a352-00155d92ca9f
2. 12ff2408-f11d-11ed-9736-00155d92ca9f
3. 1349f6cc-f11d-11ed-984a-00155d92ca9f
4. 22e0e348-f11d-11ed-bd0b-00155dc37a7b
5. 22e2cce4-f11d-11ed-a04a-00155dc37a7b
6. 2ef587c4-f11d-11ed-adbe-00155dc37a7b
7. 2f03d266-f11d-11ed-b339-00155dc37a7b

**Comment by jordan-ahn** [comment]
Adding the run IDs from my batch with the same "record_linkage" error.

1. 1b9c6b9a-f0e9-11ed-ba0d-00155dff47a2
2. 1b3d9732-f0e9-11ed-8358-00155dff47a2
3. 1b3d9732-f0e9-11ed-8358-00155dff47a2
4. 0f3ffad8-f0e9-11ed-8358-00155dff47a2

**Comment by DanPaseltiner** [comment]
Met with Saran on 05-15-2023 to review record linkage service logs. This is the traceback we are seeing:
```
2023-05-15T20:20:45.20010  Successfully Connected to container: 'phdi-uat-record-linkage' [Revision: 'phdi-uat-record-linkage--x37zktt', Replica: 'phdi-uat-record-linkage--x37zktt-cd54b4997-shkst']
2023-05-15T20:20:34.694789662Z     await self.app(scope, receive, sender)
2023-05-15T20:20:34.694793599Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-05-15T20:20:34.694797056Z     raise e
2023-05-15T20:20:34.694800542Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-15T20:20:34.694804269Z     await self.app(scope, receive, send)
2023-05-15T20:20:34.694808106Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-05-15T20:20:34.694812054Z     await route.handle(scope, receive, send)
2023-05-15T20:20:34.694815651Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-05-15T20:20:34.694819347Z     await self.app(scope, receive, send)
2023-05-15T20:20:34.694822844Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-05-15T20:20:34.694826511Z     response = await func(request)
2023-05-15T20:20:34.694830127Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
2023-05-15T20:20:34.694833574Z     raw_response = await run_endpoint_function(
2023-05-15T20:20:34.694837171Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-15T20:20:34.694840967Z     return await dependant.call(**values)
2023-05-15T20:20:34.694844564Z   File "/code/app/main.py", line 200, in link_record
2023-05-15T20:20:34.694848461Z     (found_match, new_person_id) = link_record_against_mpi(
2023-05-15T20:20:34.694861205Z   File "/usr/local/lib/python3.10/site-packages/phdi/linkage/link.py", line 606, in link_record_against_mpi
2023-05-15T20:20:34.694865533Z     blocked_record[j] = blocked_record[j][0]
2023-05-15T20:20:34.694868699Z IndexError: list index out of range
2023-05-15T20:21:45.55620  No logs since last 60 seconds
2023-05-15T20:22:45.89962  No logs since last 60 seconds
```

**Comment by DanPaseltiner** [comment]
Based on a review of the loops on lines 598 through 606 in `linkage.py` it appears that we cannot handle flattening records within a block that are returned with one or more fields that are empty lists. The small snippet below recreates the Exception we are seeing. 

```>>> test = []
>>> test[0]
Traceback (most recent call last):
  File “<stdin>“, line 1, in <module>
IndexError: list index out of range
```

This is exactly the situation that is created on line 606 `blocked_record[j] = blocked_record[j][0]` if `blocked_record[j]` is an empty list.

**Comment by DanPaseltiner** [comment]
With the record linkage service and MPI spun up on my local POSTing a dummy FHIR bundle without an MRN succeeds initially (not match is expected b/c no data in MPI yet):
![image.png](https://images.zenhubusercontent.com/63fa6366bfddeef3baa1b624/92aee9a5-c786-4fa1-a3a3-31f4cf677865)

However, if we POST this same record again the 500 internal server error is recreated:
![image.png](https://images.zenhubusercontent.com/63fa6366bfddeef3baa1b624/e44be5e7-b72f-4c19-aa4d-81610f281bde)

The same traceback we observed in LAC Azure was generated:
```
record-linkage-record-linkage-1  | INFO:     172.18.0.1:54352 - "POST /link-record HTTP/1.1" 500 Internal Server Error
record-linkage-record-linkage-1  | ERROR:    Exception in ASGI application
record-linkage-record-linkage-1  | Traceback (most recent call last):
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
record-linkage-record-linkage-1  |     result = await app(  # type: ignore[func-returns-value]
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
record-linkage-record-linkage-1  |     return await self.app(scope, receive, send)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
record-linkage-record-linkage-1  |     await super().__call__(scope, receive, send)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
record-linkage-record-linkage-1  |     await self.middleware_stack(scope, receive, send)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
record-linkage-record-linkage-1  |     raise exc
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
record-linkage-record-linkage-1  |     await self.app(scope, receive, _send)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
record-linkage-record-linkage-1  |     raise exc
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
record-linkage-record-linkage-1  |     await self.app(scope, receive, sender)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
record-linkage-record-linkage-1  |     raise e
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
record-linkage-record-linkage-1  |     await self.app(scope, receive, send)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
record-linkage-record-linkage-1  |     await route.handle(scope, receive, send)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
record-linkage-record-linkage-1  |     await self.app(scope, receive, send)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
record-linkage-record-linkage-1  |     response = await func(request)
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
record-linkage-record-linkage-1  |     raw_response = await run_endpoint_function(
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
record-linkage-record-linkage-1  |     return await dependant.call(**values)
record-linkage-record-linkage-1  |   File "/code/app/main.py", line 200, in link_record
record-linkage-record-linkage-1  |     (found_match, new_person_id) = link_record_against_mpi(
record-linkage-record-linkage-1  |   File "/usr/local/lib/python3.10/site-packages/phdi/linkage/link.py", line 606, in link_record_against_mpi
record-linkage-record-linkage-1  |     blocked_record[j] = blocked_record[j][0]
record-linkage-record-linkage-1  | IndexError: list index out of range
```
This failure occurred the second time we submitted this record to the service for linkage because there was data in the MPI to include in a block from the initial request. However, this record does not have a valid MRN so an empty list was returned and when we tried to flatten that list on line 606 this exception was raised causing the internal server error.

PR to follow shortly.

**Comment by DanPaseltiner** [comment]
With the changes in the PR linked above we can repeat our test.

POST record initially (same result as before):
![image.png](https://images.zenhubusercontent.com/63fa6366bfddeef3baa1b624/44f85ef6-3a48-40b1-b006-09786f8cefde)

POST record a second time (record is linked appropriately and no error is thrown)
![image.png](https://images.zenhubusercontent.com/63fa6366bfddeef3baa1b624/4ee60125-01a4-4eb4-9ebc-7b671a15c776)

Everything seems to be working correctly.
